### ISSUE TITLE
Package config files

### ISSUE THREAD

**Issue by kroltan** [Troposphir/troposync#12]
When creating a packaged version of the application using either `package` or `make`, the `sync.json` file is not copied to the correct location, causing the launcher to fail to start.

electron-userland/electron-forge#135 might be of help.

**Comment by kroltan** [comment]
Instead of moving the files, I changed the config to be `require`d as a module, now it packages correctly.
As for the project root (.sync), it is created dynamically.

@pedroslopez Just need you to test the latest commit on Mac, this seems done.

**Comment by pedroslopez** [comment]
Confirmed working on mac.
